"""empty message

Revision ID: 08112bcd4571
Revises: 2836d7b96d6c
Create Date: 2023-01-26 14:50:38.350204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08112bcd4571'
down_revision = '2836d7b96d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_type', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('user', sa.Column('user_type', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('exp_qual', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'exp_qual')
    op.drop_column('user', 'user_type')
    op.drop_table('profile')
    # ### end Alembic commands ###
