"""empty message

Revision ID: 613b2a44cad8
Revises: 08112bcd4571
Create Date: 2023-01-27 14:26:31.207352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613b2a44cad8'
down_revision = '08112bcd4571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rating', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rating')
    # ### end Alembic commands ###
