"""empty message

Revision ID: a1f5cc72e1f5
Revises: cda0e6c506df
Create Date: 2023-01-23 14:17:37.602246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f5cc72e1f5'
down_revision = 'cda0e6c506df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('picture', sa.VARCHAR(length=500), nullable=False))
    # ### end Alembic commands ###
