"""empty message

Revision ID: fa36e4061b35
Revises: a1f5cc72e1f5
Create Date: 2023-01-24 13:23:22.273959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa36e4061b35'
down_revision = 'a1f5cc72e1f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('date', sa.DateTime()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'date')
    # ### end Alembic commands ###
